import { useState, type FormEvent } from 'react'
import { CalendarPlus, LockKeyhole, Globe2, ChevronRight, LogOut } from 'lucide-react'
import { BottomNav, Card } from '../../components'
import type { CreateMatch, Match } from '../../types'

export function MatchesPage({ matches, onSelect, onCreate, onLogout, onHome, onPlayers }: { matches: Match[]; onSelect: (match: Match) => void; onCreate: () => void; onLogout: () => void; onHome: () => void; onPlayers: () => void }) {
  const [tab, setTab] = useState<'mine' | 'public'>('mine')
  const visibleMatches = tab === 'mine' ? matches : matches.filter(match => match.privacy === 'public')
  return <div className="phone matches-page"><header className="welcome"><div><b>TURMA ARENA 8</b><h2>Suas turmas de jogo</h2></div><div className="header-actions"><button className="round-add" onClick={onCreate} aria-label="Cadastrar pelada"><CalendarPlus /></button><button className="logout-button" onClick={onLogout} aria-label="Sair"><LogOut /></button></div></header><div className="matches-intro"><span>PELADAS</span><h1>Suas turmas de jogo</h1><p>Veja as peladas em que você joga e as turmas públicas abertas para entrar.</p><div className="match-tabs"><button className={tab === 'mine' ? 'active' : ''} onClick={() => setTab('mine')}>Minhas</button><button className={tab === 'public' ? 'active' : ''} onClick={() => setTab('public')}>Públicas</button></div></div><div className="section-title"><h2>{tab === 'mine' ? 'Minhas peladas' : 'Peladas públicas'}</h2><b>{visibleMatches.length} encontradas</b></div>{visibleMatches.length === 0 ? <Card><p>Nenhuma pelada encontrada ainda.</p></Card> : <div className="match-list">{visibleMatches.map(match => <button className="match-item" key={match.id} onClick={() => onSelect(match)}><span className="match-date">{new Date(match.date).toLocaleDateString('pt-BR', { day: '2-digit', month: 'short' })}</span><span className="match-content"><strong>{match.title}</strong><small>{new Date(match.date).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })} · {match.venue}</small><em>{match.privacy === 'private' ? <><LockKeyhole /> Privada</> : <><Globe2 /> Pública</>}</em></span><ChevronRight /></button>)}</div>}<button className="primary matches-create" onClick={onCreate}>Criar pelada</button><BottomNav active="matches" onHome={onHome} onMatches={() => setTab('mine')} onPlayers={onPlayers} /></div>
}

export function CreateMatchPage({ email, onBack, onCreated }: { email: string; onBack: () => void; onCreated: (match: CreateMatch) => Promise<void> }) {
  const [form, setForm] = useState<CreateMatch>({ title: 'Quinta no Arena 8', date: '2026-08-20T20:00', venue: 'Arena 8 - Quadra 2', maxPlayers: 16, privacy: 'private', creatorEmail: email, invitedEmails: [], moderatorEmails: [], notes: '' })
  const [invite, setInvite] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const update = (patch: Partial<CreateMatch>) => setForm(current => ({ ...current, ...patch }))
  const addInvite = () => { const value = invite.trim().toLowerCase(); if (value && value.includes('@') && !form.invitedEmails.includes(value)) update({ invitedEmails: [...form.invitedEmails, value] }); setInvite('') }
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form.title || !form.venue || form.invitedEmails.some(item => !item.includes('@'))) return setError('Preencha os dados da pelada e revise os convidados.'); setSaving(true); try { await onCreated(form) } catch { setError('Não foi possível criar a pelada agora.') } finally { setSaving(false) } }
  return <div className="phone create-match-page"><header className="welcome"><div><b>TURMA ARENA 8</b><h2>Nova pelada</h2></div></header><Card className="create-match-card"><p className="create-eyebrow">NOVA PELADA</p><h1>Criar pelada</h1><p>Defina os detalhes do jogo e quem vai moderar a lista de presença.</p><form onSubmit={submit}><label>Nome da pelada<input value={form.title} onChange={event => update({ title: event.target.value })} /></label><div className="form-columns"><label>Data<input type="datetime-local" value={form.date} onChange={event => update({ date: event.target.value })} /></label><label>Vagas<input type="number" min="2" max="100" value={form.maxPlayers} onChange={event => update({ maxPlayers: Number(event.target.value) })} /></label></div><label>Local<input value={form.venue} onChange={event => update({ venue: event.target.value })} /></label><fieldset><legend>Privacidade</legend><div className="privacy-options"><button type="button" className={form.privacy === 'private' ? 'selected' : ''} onClick={() => update({ privacy: 'private' })}><LockKeyhole />Privada<small>Apenas convidados</small></button><button type="button" className={form.privacy === 'public' ? 'selected' : ''} onClick={() => update({ privacy: 'public' })}><Globe2 />Pública<small>Qualquer pessoa pode entrar</small></button></div></fieldset>{form.privacy === 'private' && <label>Convidados<small className="field-help">Adicione os e-mails autorizados a visualizar a pelada.</small><div className="invite-row"><input value={invite} onChange={event => setInvite(event.target.value)} placeholder="convidado@email.com" type="email" /><button type="button" onClick={addInvite}>Adicionar</button></div><div className="invite-list">{form.invitedEmails.map(item => <span key={item}>{item}<button type="button" onClick={() => update({ invitedEmails: form.invitedEmails.filter(email => email !== item) })}>×</button></span>)}</div></label>}<label>Observações<textarea value={form.notes} onChange={event => update({ notes: event.target.value })} placeholder="Ex.: levar colete claro e escuro, rateio de R$ 20." /></label>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={saving}>{saving ? 'Criando pelada...' : 'Criar pelada'}</button></form></Card><button className="auth-footer create-back" onClick={onBack}>Quer voltar? <strong>Ir para as peladas</strong></button></div>
}
