import { X } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import type { CreatePlayer, Player } from '../types'
import { Avatar } from './Avatar'
import { Card } from './Card'
import { StarPicker } from './StarPicker'

type Props = { player?: Player; onClose: () => void; onSave: (player: CreatePlayer) => Promise<void> };
export function PlayerForm({ player, onClose, onSave }: Props) { const [form, setForm] = useState<CreatePlayer>(() => player ? { name: player.name, position: player.position, level: player.level, trait: player.trait } : { name: '', position: '', level: 5, trait: '' }); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const editing = Boolean(player); const initials = form.name ? form.name.split(' ').filter(Boolean).slice(0, 2).map(name => name[0]).join('').toUpperCase() : 'JJ'; const submit = async (event: FormEvent) => { event.preventDefault(); if (!form.name.trim() || !form.position) return setError('Preencha nome e posição principal.'); setSaving(true); setError(''); try { await onSave(form); } catch { setError('Não foi possível salvar agora. Tente novamente.'); } finally { setSaving(false); } }; return <div className="form-dialog"><div className="drawer-backdrop" onClick={onClose}/><Card className="form-dialog-content"><header><div><small>{editing ? 'EDITAR JOGADOR' : 'NOVO JOGADOR'}</small><h1>{editing ? 'Editar perfil' : 'Cadastro de jogador'}</h1></div><button className="icon-button" onClick={onClose}><X /></button></header><div className="profile-placeholder"><Avatar initials={initials}/><p>Perfil usado para equilibrar os times.</p></div><form onSubmit={submit}><label>Nome completo<input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="Ex.: Gabriel Santos" autoFocus/></label><label>Posição principal<select value={form.position} onChange={event => setForm({ ...form, position: event.target.value })}><option value="">Selecione uma posição</option><option>Goleiro</option><option>Fixo</option><option>Ala</option><option>Pivô</option></select></label><label>Nível de jogo <span>{form.level.toLocaleString('pt-BR')}/10</span><StarPicker level={form.level} onChange={level => setForm({ ...form, level })}/></label><div className="level-hint"><small>Iniciante</small><small>Intermediário</small><small>Avançado</small></div><label>Principal característica <em>opcional</em><input value={form.trait} onChange={event => setForm({ ...form, trait: event.target.value })} placeholder="Ex.: passe e velocidade"/></label>{error && <p className="form-error">{error}</p>}<button className="primary save-player" disabled={saving}>{saving ? 'Salvando...' : editing ? 'Salvar alterações' : 'Salvar jogador'}</button></form></Card></div>; }
