import { useState, type FormEvent, type ReactNode } from 'react'
import { AuthBrand } from './components/AuthBrand'
import { AuthField } from './components/AuthField'

type LoginProps = { onLogin: (email: string, password: string) => void; onRegister: () => void }
type RegisterProps = { onRegister: (name: string, email: string, password: string, position: string) => void; onLogin: () => void }

export function LoginPage({ onLogin, onRegister }: LoginProps) { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const submit = (event: FormEvent) => { event.preventDefault(); if (!email || password.length < 6) return setError('Informe um e-mail e uma senha com pelo menos 6 caracteres.'); try { onLogin(email, password) } catch { setError('E-mail ou senha inválidos.') } }; return <AuthFrame eyebrow="QUINTA NO ARENA 8" title="Entrar na sua turma" description="Use seu e-mail para confirmar presença e acompanhar as escalações."><form onSubmit={submit}><AuthField label="E-mail" value={email} onChange={event => setEmail(event.target.value)} placeholder="voce@email.com" type="email" autoComplete="email" required /><AuthField label="Senha" value={password} onChange={event => setPassword(event.target.value)} placeholder="••••••••" password autoComplete="current-password" required /><div className="auth-helper"><span>Esqueceu a senha?</span><button type="button" onClick={() => setError('Entre em contato com o administrador da turma para recuperar o acesso.')}>Recuperar acesso</button></div>{error && <p className="auth-error" role="alert">{error}</p>}<button className="auth-primary" type="submit">Entrar</button><button className="auth-secondary" type="button" onClick={() => setError('O convite da turma será disponibilizado pelo administrador.')}>Entrar com convite da turma</button></form><AuthFooter>Ainda não tem conta? <button onClick={onRegister}>Criar cadastro</button></AuthFooter></AuthFrame> }

export function RegisterPage({ onRegister, onLogin }: RegisterProps) { const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [position, setPosition] = useState('Ala'); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const submit = (event: FormEvent) => { event.preventDefault(); if (!name || !email || password.length < 6 || password !== confirm) return setError(password !== confirm ? 'As senhas precisam ser iguais.' : 'Preencha os campos com uma senha de pelo menos 6 caracteres.'); onRegister(name, email, password, position) }; return <AuthFrame eyebrow="NOVA CONTA" title="Criar cadastro" description="Seu perfil entra no cálculo de equilíbrio dos times."><form onSubmit={submit}><AuthField label="Nome ou apelido" value={name} onChange={event => setName(event.target.value)} placeholder={'Ex.: Rafael "Muralha"'} autoComplete="name" required /><AuthField label="E-mail" value={email} onChange={event => setEmail(event.target.value)} placeholder="voce@email.com" type="email" autoComplete="email" required /><label className="auth-field"><span>Posição preferida</span><div className="position-grid">{['Goleiro', 'Fixo', 'Ala', 'Pivô'].map(item => <button type="button" className={position === item ? 'selected' : ''} onClick={() => setPosition(item)} key={item}>{item}</button>)}</div></label><AuthField label="Senha" value={password} onChange={event => setPassword(event.target.value)} placeholder="••••••••" password autoComplete="new-password" required /><small className="password-hint">Mínimo de 6 caracteres.</small><AuthField label="Confirmar senha" value={confirm} onChange={event => setConfirm(event.target.value)} placeholder="••••••••" password autoComplete="new-password" required />{error && <p className="auth-error" role="alert">{error}</p>}<div className="auth-note">Ao criar a conta você entra na fila da <strong>Quinta no Arena 8</strong> e recebe convite quando abrir vaga.</div><button className="auth-primary" type="submit">Criar conta</button></form><AuthFooter>Já joga com a gente? <button onClick={onLogin}>Entrar</button></AuthFooter></AuthFrame> }

function AuthFrame({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: ReactNode }) { return <div className="auth-page"><AuthBrand /><section className="auth-card"><p className="auth-eyebrow">{eyebrow}</p><h1>{title}</h1><p className="auth-description">{description}</p>{children}</section></div> }
function AuthFooter({ children }: { children: ReactNode }) { return <div className="auth-footer">{children}</div> }