import { CalendarDays, ChevronLeft, Home, Shirt, Star, UserRound, UsersRound } from 'lucide-react'
import type { PropsWithChildren } from 'react'
import type { Player, Team } from './types'

export function Avatar({ initials }: { initials: string }) { return <span className="avatar">{initials}</span> }
export function Card({ children, className = '' }: PropsWithChildren<{ className?: string }>) { return <section className={`card ${className}`}>{children}</section> }
export function BackButton({ onClick }: { onClick: () => void }) { return <button className="icon-button" onClick={onClick} aria-label="Voltar"><ChevronLeft /></button> }
export function PageHeader({ eyebrow, title, onBack }: { eyebrow: string; title: string; onBack: () => void }) { return <header className="page-head"><BackButton onClick={onBack} /><div><b>{eyebrow}</b><h1>{title}</h1></div><Shirt /></header> }
export function BottomNav({ active = 'home', onHome, onMatches, onPlayers }: { active?: 'home' | 'matches' | 'players'; onHome?: () => void; onMatches?: () => void; onPlayers?: () => void }) { return <nav className="bottom-nav"><button className={active === 'home' ? 'active' : ''} onClick={onHome}><Home />Início</button><button className={active === 'matches' ? 'active' : ''} onClick={onMatches}><CalendarDays />Peladas</button><button className={active === 'players' ? 'active' : ''} onClick={onPlayers}><UsersRound />Jogadores</button><button><UserRound />Perfil</button></nav> }
export function LevelStars({ level, compact = false }: { level: number; compact?: boolean }) { return <span className={`level-stars ${compact ? 'compact' : ''}`} role="img" aria-label={`Nível ${level} de 10`} title={`Nível ${level}/10`}>{Array.from({ length: 10 }, (_, index) => { const star = index + 1; return <span className={`display-star ${level >= star ? 'filled' : ''}`} key={star}><Star fill={level >= star ? 'currentColor' : 'none'} />{level === star - .5 && <span className="display-half"><Star fill="currentColor" /></span>}</span> })}</span> }
export function StarPicker({ level, onChange }: { level: number; onChange: (level: number) => void }) { return <div className="star-picker" role="group" aria-label="Nível de jogo, de 1 a 10 em intervalos de meio ponto">{Array.from({ length: 10 }, (_, index) => { const star = index + 1; const half = level === star - .5; return <span className={`picker-star ${level >= star ? 'filled' : ''}`} key={star}><Star fill={level >= star ? 'currentColor' : 'none'} />{half && <span className="half-star"><Star fill="currentColor" /></span>}<button type="button" className="star-half left" onClick={() => onChange(star - .5)} aria-label={`${star - .5} estrelas`} /><button type="button" className="star-half right" onClick={() => onChange(star)} aria-label={`${star} estrelas`} /></span> })}</div> }
export function PlayerRow({ player, score = false }: { player: Player; score?: boolean }) { return <div className="player-row"><Avatar initials={player.initials} /><div><strong>{player.name}</strong><small>{player.position} · {player.trait}</small></div>{score ? <span className="rating">{player.level}</span> : <span className="level">Nível {player.level.toLocaleString('pt-BR')}</span>}</div> }
export function TeamCard({ team }: { team: Team }) { return <Card className={`team-card ${team.color}`}><header><h3>{team.name}</h3><small>Média {team.averageLevel.toFixed(1)} · {team.color === 'blue' ? 'Defesa sólida' : 'Criação forte'}</small></header><div className="captain">Capitão: {team.players[0]?.name.split(' ')[0]}</div>{team.players.map(player => <PlayerRow key={player.id} player={player} score />)}</Card> }