export type Sport = 'Futebol' | 'Futsal' | 'Voleibol de quadra' | 'Vôlei de areia';
export type Player = { id: string; name: string; initials: string; position: string; level: number; trait: string; sports?: Sport[] };
export type CreatePlayer = { name: string; position: string; level: number; trait?: string; sports?: Sport[] };
export type ParticipantRole = 'administrator' | 'moderator' | 'participant';
export type MatchPermissions = { canView: boolean; canConfirmPresence: boolean; canModeratePresence: boolean; canGenerateTeams: boolean; canManageMatch: boolean; canManageParticipants: boolean };
export type Match = { id: string; title: string; date: string; venue: string; maxPlayers: number; confirmedCount: number; players: Player[]; privacy: 'public' | 'private'; creatorEmail?: string; invitedEmails: string[]; currentRole?: ParticipantRole; permissions?: MatchPermissions };
export type CreateMatch = { title: string; date: string; venue: string; maxPlayers: number; privacy: 'public' | 'private'; creatorEmail: string; invitedEmails: string[]; moderatorEmails: string[]; notes?: string };
export type Team = { name: string; color: string; totalLevel: number; averageLevel: number; players: Player[] };
export type TeamsResult = { balancePercentage: number; teams: Team[]; explanation: string };
